[tools]

node = "25"
bun = "latest"
# python = "3.11.11"
elixir = "latest"

[plugins]
# python = 'https://github.com/jdxcode/rtx-python'

[settings]
experimental = true
#idiomatic_version_file_enable_tools = ["python"]
